packages:
  - packages/*

catalog:
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  react: ^19.2.7
  react-dom: ^19.2.7

onlyBuiltDependencies:
  - esbuild
  - sharp
  - tldjs

overrides:
  hono: '>=4.12.2'
