packages:
  - packages/*

catalog:
  '@types/react': ^19.1.15
  react: ^19.1.1

onlyBuiltDependencies:
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  '@nemo-cli/package': link:packages/package
