packages:
  - packages/*

catalog:
  '@types/react': ^19.2.11
  '@types/react-dom': ^19.2.3
  react: ^19.2.4
  react-dom: ^19.2.4

onlyBuiltDependencies:
  - esbuild
  - sharp
  - tldjs

overrides:
  hono: '>=4.11.4'
