packages:
  - packages/*

catalog:
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  react: ^19.2.0
  react-dom: ^19.2.0

onlyBuiltDependencies:
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  '@nemo-cli/package': link:packages/package
