name: create-excalidraw-wireframe
description: "Create website or app wireframes in Excalidraw format"
author: "BMad"

# Config values
config_source: "{project-root}/.bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/diagrams/create-wireframe"
shared_path: "{project-root}/.bmad/bmm/workflows/diagrams/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Core Excalidraw resources (universal knowledge)
helpers: "{project-root}/.bmad/core/resources/excalidraw/excalidraw-helpers.md"
json_validation: "{project-root}/.bmad/core/resources/excalidraw/validate-json-instructions.md"

# Domain-specific resources (technical diagrams)
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

# Output file (respects user's configured output_folder)
default_output_file: "{output_folder}/diagrams/wireframe-{timestamp}.excalidraw"

standalone: true