# Edit Agent - Agent Editor Configuration
name: "edit-agent"
description: "Edit existing BMAD agents while following all best practices and conventions"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/.bmad/bmb/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Required Data Files - Critical for understanding agent conventions

# Core Concepts
understanding_agent_types: "{project-root}/.bmad/bmb/docs/understanding-agent-types.md"
agent_compilation: "{project-root}/.bmad/bmb/docs/agent-compilation.md"

# Architecture Guides (Simple, Expert, Module)
simple_architecture: "{project-root}/.bmad/bmb/docs/simple-agent-architecture.md"
expert_architecture: "{project-root}/.bmad/bmb/docs/expert-agent-architecture.md"
module_architecture: "{project-root}/.bmad/bmb/docs/module-agent-architecture.md"

# Design Patterns
menu_patterns: "{project-root}/.bmad/bmb/docs/agent-menu-patterns.md"
communication_presets: "{project-root}/.bmad/bmb/workflows/create-agent/communication-presets.csv"
brainstorm_context: "{project-root}/.bmad/bmb/workflows/create-agent/brainstorm-context.md"

# Workflow execution engine reference
workflow_execution_engine: "{project-root}/.bmad/core/tasks/workflow.xml"

# Reference Agents - Clean implementations showing best practices
reference_agents: "{project-root}/.bmad/bmb/reference/agents/"
reference_simple_agent: "{reference_agents}/simple-examples/commit-poet.agent.yaml"
reference_expert_agent: "{reference_agents}/expert-examples/journal-keeper/journal-keeper.agent.yaml"
reference_module_agents: "{reference_agents}/module-examples/"

# BMM Agents - Examples of distinct communication voices
bmm_agents: "{project-root}/.bmad/bmm/agents/"

# Module path and component files
installed_path: "{project-root}/.bmad/bmb/workflows/edit-agent"
template: false # This is an action workflow - no template needed
instructions: "{installed_path}/instructions.md"
# Shared validation checklist (canonical location in create-agent folder)
validation: "{project-root}/.bmad/bmb/workflows/create-agent/agent-validation-checklist.md"

standalone: true

# Web bundle configuration