# Innovation Strategy Workflow Configuration
name: "innovation-strategy"
description: 'Identify disruption opportunities and architect business model innovation. Use when the user says "lets create an innovation strategy" or "I want to find disruption opportunities"'

# Critical variables load from config_source
config_source: "{project-root}/_bmad/cis/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Context can be provided via data attribute when invoking
# Example: data="{path}/industry-analysis.md" provides market context

# Module path and component files
installed_path: "{project-root}/_bmad/cis/workflows/innovation-strategy"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Required Data Files
innovation_frameworks: "{installed_path}/innovation-frameworks.csv"

# Output configuration
default_output_file: "{output_folder}/innovation-strategy-{{date}}.md"

standalone: true
