# Party Mode - Multi-Agent Group Discussion Workflow
name: "party-mode"
description: "Orchestrates group discussions between all installed BMAD agents, enabling natural multi-agent conversations"
author: "BMad"

# Critical data sources - manifest and config overrides
agent_manifest: "{project-root}/.bmad/_cfg/agent-manifest.csv"
date: system-generated

# This is an interactive action workflow - no template output
template: false
instructions: "{project-root}/.bmad/core/workflows/party-mode/instructions.md"

# Exit conditions
exit_triggers:
  - "*exit"

standalone: true

web_bundle:
  name: "party-mode"
  description: "Orchestrates group discussions between all installed BMAD agents, enabling natural multi-agent conversations"
  author: "BMad"
  instructions: ".bmad/core/workflows/party-mode/instructions.md"
  agent_manifest: ".bmad/_cfg/agent-manifest.csv"
  web_bundle_files:
    - ".bmad/core/workflows/party-mode/instructions.md"
    - ".bmad/_cfg/agent-manifest.csv"
